title: mattsclancy
description: Data and statistics work of public interest.
url: "https://mattsclancy.github.io"
baseurl: ""

theme: minima
future: true
permalink: /:year/:month/:day/:title:output_ext

minima:
  date_format: "%B %-d, %Y"

plugins:
  - jekyll-feed

author:
  name: Matt Clancy
